apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-hello.fullname" . }}
  labels:
    {{- include "node-hello.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "node-hello.selectorLabels" . | nindent 4 }}
