replicaCount: 1

image:
  repository: pranshu98/node-hello
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 3000
  nodePort: 30000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

nodeSelector: {}

tolerations: {}

affinity: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  automount: true
